#======================================================#
#  Set the programs you want to start when you log in  #
#======================================================#

exec-once = waybar & hyprpaper
exec-once = protonvpn-app
exec-once = systemctl --user start opentabletdriver
