#======================================================#
#  Set the programs you want to start when you log in  #
#======================================================#

exec-once = waybar & hyprpaper
