#==============#
#  Something?  #
#==============#
# I supose it is necesary so I dont will delete this lines of the main config

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    col.splash = rgba(255, 255, 255, 0.0)
}
