#=======================================#
#    Put your variables in this file    #
#=======================================#


# Program variables

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$gamehub = steam
$browser = firefox

# Enviroment variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
